# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from service import diffusion_processing_pb2 as diffusion__processing__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in diffusion_processing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageGeneratorStub(object):
    """이미지 생성 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateImage = channel.unary_unary(
                '/ImageGenerator/GenerateImage',
                request_serializer=diffusion__processing__pb2.GenerationRequest.SerializeToString,
                response_deserializer=diffusion__processing__pb2.GenerationResponse.FromString,
                _registered_method=True)


class ImageGeneratorServicer(object):
    """이미지 생성 서비스
    """

    def GenerateImage(self, request, context):
        """이미지 생성 요청
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageGeneratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateImage,
                    request_deserializer=diffusion__processing__pb2.GenerationRequest.FromString,
                    response_serializer=diffusion__processing__pb2.GenerationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageGenerator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ImageGenerator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageGenerator(object):
    """이미지 생성 서비스
    """

    @staticmethod
    def GenerateImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImageGenerator/GenerateImage',
            diffusion__processing__pb2.GenerationRequest.SerializeToString,
            diffusion__processing__pb2.GenerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
