# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: diffusion_processing.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'diffusion_processing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x64iffusion_processing.proto\"\x99\x01\n\x11GenerationRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x16\n\x0eguidance_scale\x18\x03 \x01(\x02\x12\x1b\n\x13num_inference_steps\x18\x04 \x01(\x05\x12\r\n\x05width\x18\x05 \x01(\x05\x12\x0e\n\x06height\x18\x06 \x01(\x05\x12\x0c\n\x04seed\x18\x07 \x01(\x03\"\xb6\x01\n\x12GenerationResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12*\n\x06status\x18\x02 \x01(\x0e\x32\x1a.GenerationResponse.Status\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x12\n\nimage_data\x18\x04 \x01(\x0c\x12\x11\n\tused_seed\x18\x05 \x01(\x03\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32J\n\x0eImageGenerator\x12\x38\n\rGenerateImage\x12\x12.GenerationRequest\x1a\x13.GenerationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'diffusion_processing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATIONREQUEST']._serialized_start=31
  _globals['_GENERATIONREQUEST']._serialized_end=184
  _globals['_GENERATIONRESPONSE']._serialized_start=187
  _globals['_GENERATIONRESPONSE']._serialized_end=369
  _globals['_GENERATIONRESPONSE_STATUS']._serialized_start=335
  _globals['_GENERATIONRESPONSE_STATUS']._serialized_end=369
  _globals['_IMAGEGENERATOR']._serialized_start=371
  _globals['_IMAGEGENERATOR']._serialized_end=445
# @@protoc_insertion_point(module_scope)
